### ISSUE TITLE
id type mismatch.

### ISSUE THREAD

**Issue by euforia** [plouc/go-gitlab-client#14]
It seems Gitlab emits an event with the project_id as an int64, but the AddProjectWebhook takes an id of type string https://github.com/plouc/go-gitlab-client/blob/master/hooks.go#L91 

Any particular reason why it was done this way or can I go ahead and do a PR with the fix?

**Comment by fudanchii** [comment]
I was hoped the comment [there](https://github.com/plouc/go-gitlab-client/blob/master/hooks.go#L84) is clear though, as specified at gitlab documentation: https://github.com/gitlabhq/gitlabhq/blob/7-11-stable/doc/api/projects.md

the id is supposed to be either project_id or a composed `namespace/project_name` so using string here is, I believe, make sense.
Using int64 will break the support for specifying id as `namespace/project_name`.

**Comment by euforia** [comment]
Ah ok.  Makes a lot more sense.  I was unaware of the fact that the namspaced path could be used as the id.  Thank you for the clarification.
